name: restaurant
description: Fraved Restaurante Copyright

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4
  image_picker: ^0.8.5+3
  form_field_validator: ^1.1.0
  android_intent_plus: ^3.1.1+1
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  geolocator: ^9.0.1
  google_maps_flutter: ^2.2.0
  permission_handler: ^10.0.0
  geocoding: ^2.0.5
  intl: ^0.17.0
  polyline_do: ^0.1.0
  url_launcher: ^6.1.5
  socket_io_client: 1.0.2
  firebase_messaging: ^13.0.0
  firebase_core: ^1.21.1
  flutter_local_notifications: ^9.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Logo/
    - assets/svg/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

